chore: deploying canary support

diff --git a/.github/workflows/deploy-storefrontcloud.yml b/.github/workflows/deploy-storefrontcloud.yml
--- a/.github/workflows/deploy-storefrontcloud.yml
+++ b/.github/workflows/deploy-storefrontcloud.yml
@@ -3,6 +3,14 @@ on:
   push:
     branches:
       - master
+  release:
+    types: [published]
+env:
+  CANARY_URL: https://shopware-pwa-canary.storefrontcloud.io
+  RELEASE_URL: https://shopware-pwa.storefrontcloud.io
+  CANARY_INSTANCE: shopware-pwa-canary
+  RELEASE_INSTANCE: shopware-pwa
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -36,20 +44,34 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
+      - name: Setup deployment variables
+        run: |
+          echo ::set-env name=DEPLOY_URL::$([[ "${{github.event_name}}" == "release" ]] && echo "$RELEASE_URL" || echo "$CANARY_URL")
+          echo ::set-env name=INSTANCE_CODE::$([[ "${{github.event_name}}" == "release" ]] && echo "$RELEASE_INSTANCE" || echo "$CANARY_INSTANCE")
       - uses: chrnorm/deployment-action@releases/v1
         name: Create GitHub deployment
+        if: github.event_name == 'release'
         id: deployment
         with:
           token: "${{ github.token }}"
-          target_url: https://shopware-pwa.storefrontcloud.io
+          target_url: ${{ env.DEPLOY_URL }}
           environment: production
+          initial_status: in_progress
+      - uses: chrnorm/deployment-action@releases/v1
+        name: Create GitHub deployment
+        if: github.event_name == 'push'
+        id: deployment
+        with:
+          token: "${{ github.token }}"
+          target_url: ${{ env.DEPLOY_URL }}
+          environment: canary
           initial_status: in_progress
       - name: Deploy on Storefrontcloud.io
         run: |
-          if curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} -H 'Content-Type: application/json' -X POST -d '{"code":"shopware-pwa","frontContainerVersion":"${{ github.sha }}"}' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
+          if curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} -H 'Content-Type: application/json' -X POST -d '{"code":"${{ env.INSTANCE_CODE }}","frontContainerVersion":"${{ github.sha }}"}' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
             echo "Instance updated"
           else
-            echo "Something went wrong during the update process..."
+            echo "Deployment failed"
             exit 1
           fi
       - name: Update deployment status (success)
@@ -57,7 +79,7 @@ jobs:
         uses: chrnorm/deployment-status@releases/v1
         with:
           token: "${{ github.token }}"
-          target_url: https://shopware-pwa.storefrontcloud.io
+          target_url: ${{ env.DEPLOY_URL }}
           state: "success"
           description: Congratulations! The deploy is done.
           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
@@ -66,7 +88,7 @@ jobs:
         uses: chrnorm/deployment-status@releases/v1
         with:
           token: "${{ github.token }}"
-          target_url: https://shopware-pwa.storefrontcloud.io
+          target_url: ${{ env.DEPLOY_URL }}
           description: Unfortunately, the instance hasn't been updated.
           state: "failure"
           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
