chore: test without deploy

diff --git a/.github/workflows/publish-canary.yml b/.github/workflows/publish-canary.yml
--- a/.github/workflows/publish-canary.yml
+++ b/.github/workflows/publish-canary.yml
@@ -11,7 +11,7 @@ on:
       - workflow/*
     # TODO: remove here
 jobs:
-  
+
   init:
     name: Init dependencies
     runs-on: ubuntu-latest
@@ -347,41 +347,41 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
           workdir: ./app
           buildoptions: "--compress"
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - uses: chrnorm/deployment-action@releases/v1
-        name: Create GitHub deployment
-        id: deployment
-        with:
-          token: "${{ github.token }}"
-          target_url: ${{ env.CANARY_URL }}
-          environment: canary
-          initial_status: in_progress
-      - name: Deploy on StorefrontCloud.io
-        run: |
-          if curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} -H 'Content-Type: application/json' -X POST -d '{"code":"${{ env.INSTANCE_CODE }}","frontContainerVersion":"${{ github.sha }}"}' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
-            echo "Instance updated"
-          else
-            echo "Deployment failed"
-            exit 1
-          fi
-      - name: Update deployment status (success)
-        if: success()
-        uses: chrnorm/deployment-status@releases/v1
-        with:
-          token: "${{ github.token }}"
-          target_url: ${{ env.CANARY_URL }}
-          state: "success"
-          description: Congratulations! The deploy is done.
-          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
-      - name: Update deployment status (failure)
-        if: failure()
-        uses: chrnorm/deployment-status@releases/v1
-        with:
-          token: "${{ github.token }}"
-          target_url: ${{ env.CANARY_URL }}
-          description: Unfortunately, the instance hasn't been updated.
-          state: "failure"
-          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   steps:
+  #     - uses: chrnorm/deployment-action@releases/v1
+  #       name: Create GitHub deployment
+  #       id: deployment
+  #       with:
+  #         token: "${{ github.token }}"
+  #         target_url: ${{ env.CANARY_URL }}
+  #         environment: canary
+  #         initial_status: in_progress
+  #     - name: Deploy on StorefrontCloud.io
+  #       run: |
+  #         if curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} -H 'Content-Type: application/json' -X POST -d '{"code":"${{ env.INSTANCE_CODE }}","frontContainerVersion":"${{ github.sha }}"}' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
+  #           echo "Instance updated"
+  #         else
+  #           echo "Deployment failed"
+  #           exit 1
+  #         fi
+  #     - name: Update deployment status (success)
+  #       if: success()
+  #       uses: chrnorm/deployment-status@releases/v1
+  #       with:
+  #         token: "${{ github.token }}"
+  #         target_url: ${{ env.CANARY_URL }}
+  #         state: "success"
+  #         description: Congratulations! The deploy is done.
+  #         deployment_id: ${{ steps.deployment.outputs.deployment_id }}
+  #     - name: Update deployment status (failure)
+  #       if: failure()
+  #       uses: chrnorm/deployment-status@releases/v1
+  #       with:
+  #         token: "${{ github.token }}"
+  #         target_url: ${{ env.CANARY_URL }}
+  #         description: Unfortunately, the instance hasn't been updated.
+  #         state: "failure"
+  #         deployment_id: ${{ steps.deployment.outputs.deployment_id }}
