feat: deploying canary - support (#662)

diff --git a/.github/workflows/publish-canary.yml b/.github/workflows/publish-canary.yml
--- a/.github/workflows/publish-canary.yml
+++ b/.github/workflows/publish-canary.yml
@@ -1,4 +1,9 @@
-name: Publish canary
+name: Publish & deploy canary version
+env:
+  CANARY_SW6_INSTANCE: https://shopware6-demo.vuestorefront.io
+  CANARY_SW6_INSTANCE_TOKEN: SWSCVJJET0RQAXFNBMTDZTV1OQ
+  CANARY_URL: https://shopware-pwa-canary.storefrontcloud.io
+  INSTANCE_CODE: shopware-pwa-canary
 on:
   push:
     branches:
@@ -24,3 +29,62 @@ jobs:
           yarn lerna publish --canary --force-publish --yes --preid prealpha --dist-tag canary
         env:
           NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install shopware-pwa cli
+        run: |
+          yarn global add @shopware-pwa/cli@canary
+      - name: Create default-theme project
+        run: |
+          mkdir app
+          cd ./app
+          shopware-pwa init --shopwareEndpoint=${{ env.CANARY_SW6_INSTANCE }} --shopwareAccessToken=${{ env.CANARY_SW6_INSTANCE_TOKEN }} --u ${{ secrets.SHOPWARE_ADMIN_USER }} --p ${{ secrets.SHOPWARE_ADMIN_PASSWORD }} --ci --devMode --stage canary
+          yarn build
+      - name: Build and publish docker image
+        uses: elgohr/Publish-Docker-Github-Action@master
+        with:
+          name: shopware-pwa-storefrontcloud-io/vue-storefront:${{ github.sha }}
+          registry: registry.storefrontcloud.io
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+          workdir: ./app
+          buildoptions: "--compress"
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: chrnorm/deployment-action@releases/v1
+        name: Create GitHub deployment
+        id: deployment
+        with:
+          token: "${{ github.token }}"
+          target_url: ${{ env.CANARY_URL }}
+          environment: canary
+          initial_status: in_progress
+      - name: Deploy on StorefrontCloud.io
+        run: |
+          if curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} -H 'Content-Type: application/json' -X POST -d '{"code":"${{ env.INSTANCE_CODE }}","frontContainerVersion":"${{ github.sha }}"}' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
+            echo "Instance updated"
+          else
+            echo "Deployment failed"
+            exit 1
+          fi
+      - name: Update deployment status (success)
+        if: success()
+        uses: chrnorm/deployment-status@releases/v1
+        with:
+          token: "${{ github.token }}"
+          target_url: ${{ env.CANARY_URL }}
+          state: "success"
+          description: Congratulations! The deploy is done.
+          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
+      - name: Update deployment status (failure)
+        if: failure()
+        uses: chrnorm/deployment-status@releases/v1
+        with:
+          token: "${{ github.token }}"
+          target_url: ${{ env.CANARY_URL }}
+          description: Unfortunately, the instance hasn't been updated.
+          state: "failure"
+          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
