chore: prepare for merge

diff --git a/.github/workflows/publish-canary.yml b/.github/workflows/publish-canary.yml
--- a/.github/workflows/publish-canary.yml
+++ b/.github/workflows/publish-canary.yml
@@ -8,8 +8,6 @@ on:
   push:
     branches:
       - master
-      - workflow/*
-    # TODO: remove here
 jobs:
   init:
     name: Init dependencies
@@ -121,7 +119,7 @@ jobs:
       - name: Build Composables
         if: steps.step-cache-build.outputs.cache-hit != 'true'
         run: |
-          yarn build composables --ci
+          yarn build composables --release
 
   build-helpers:
     name: Build helpers package
@@ -164,7 +162,7 @@ jobs:
       - name: Build helpers
         if: steps.step-cache-build.outputs.cache-hit != 'true'
         run: |
-          yarn build helpers --ci
+          yarn build helpers --release
 
   build-nuxt-module:
     name: Build nuxt-module package
@@ -207,7 +205,7 @@ jobs:
       - name: Build nuxt-module
         if: steps.step-cache-build.outputs.cache-hit != 'true'
         run: |
-          yarn build nuxt-module --ci
+          yarn build nuxt-module --release
 
   build-shopware-6-client:
     name: Build shopware-6-client package
@@ -250,7 +248,7 @@ jobs:
       - name: Build shopware-6-client
         if: steps.step-cache-build.outputs.cache-hit != 'true'
         run: |
-          yarn build shopware-6-client --ci
+          yarn build shopware-6-client --release
 
   publish:
     name: Publish version
@@ -325,64 +323,64 @@ jobs:
           key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
       - name: Publish canary version
         run: |
-          yarn release --canary --skipBuild --dry
+          yarn release --canary --skipBuild
         env:
           NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
 
-  # build:
-  #   runs-on: ubuntu-latest
-  #   needs: publish
-  #   steps:
-  #     - name: Create default-theme project
-  #       run: |
-  #         mkdir app
-  #         cd ./app
-  #         npx @shopware-pwa/cli@canary init --shopwareEndpoint=${{ env.CANARY_SW6_INSTANCE }} --shopwareAccessToken=${{ env.CANARY_SW6_INSTANCE_TOKEN }} --u ${{ secrets.SHOPWARE_ADMIN_USER }} --p ${{ secrets.SHOPWARE_ADMIN_PASSWORD }} --ci --devMode --stage canary
-  #         yarn build
-  #     - name: Build and publish docker image
-  #       uses: elgohr/Publish-Docker-Github-Action@master
-  #       with:
-  #         name: shopware-pwa-storefrontcloud-io/vue-storefront:${{ github.sha }}
-  #         registry: registry.storefrontcloud.io
-  #         username: ${{ secrets.DOCKER_USERNAME }}
-  #         password: ${{ secrets.DOCKER_PASSWORD }}
-  #         workdir: ./app
-  #         buildoptions: "--compress"
-  # deploy:
-  #   runs-on: ubuntu-latest
-  #   needs: build
-  #   steps:
-  #     - uses: chrnorm/deployment-action@releases/v1
-  #       name: Create GitHub deployment
-  #       id: deployment
-  #       with:
-  #         token: "${{ github.token }}"
-  #         target_url: ${{ env.CANARY_URL }}
-  #         environment: canary
-  #         initial_status: in_progress
-  #     - name: Deploy on StorefrontCloud.io
-  #       run: |
-  #         if curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} -H 'Content-Type: application/json' -X POST -d '{"code":"${{ env.INSTANCE_CODE }}","frontContainerVersion":"${{ github.sha }}"}' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
-  #           echo "Instance updated"
-  #         else
-  #           echo "Deployment failed"
-  #           exit 1
-  #         fi
-  #     - name: Update deployment status (success)
-  #       if: success()
-  #       uses: chrnorm/deployment-status@releases/v1
-  #       with:
-  #         token: "${{ github.token }}"
-  #         target_url: ${{ env.CANARY_URL }}
-  #         state: "success"
-  #         description: Congratulations! The deploy is done.
-  #         deployment_id: ${{ steps.deployment.outputs.deployment_id }}
-  #     - name: Update deployment status (failure)
-  #       if: failure()
-  #       uses: chrnorm/deployment-status@releases/v1
-  #       with:
-  #         token: "${{ github.token }}"
-  #         target_url: ${{ env.CANARY_URL }}
-  #         description: Unfortunately, the instance hasn't been updated.
-  #         state: "failure"
-  #         deployment_id: ${{ steps.deployment.outputs.deployment_id }}
+  build:
+    runs-on: ubuntu-latest
+    needs: publish
+    steps:
+      - name: Create default-theme project
+        run: |
+          mkdir app
+          cd ./app
+          npx @shopware-pwa/cli@canary init --shopwareEndpoint=${{ env.CANARY_SW6_INSTANCE }} --shopwareAccessToken=${{ env.CANARY_SW6_INSTANCE_TOKEN }} --u ${{ secrets.SHOPWARE_ADMIN_USER }} --p ${{ secrets.SHOPWARE_ADMIN_PASSWORD }} --ci --devMode --stage canary
+          yarn build
+      - name: Build and publish docker image
+        uses: elgohr/Publish-Docker-Github-Action@master
+        with:
+          name: shopware-pwa-storefrontcloud-io/vue-storefront:${{ github.sha }}
+          registry: registry.storefrontcloud.io
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+          workdir: ./app
+          buildoptions: "--compress"
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: chrnorm/deployment-action@releases/v1
+        name: Create GitHub deployment
+        id: deployment
+        with:
+          token: "${{ github.token }}"
+          target_url: ${{ env.CANARY_URL }}
+          environment: canary
+          initial_status: in_progress
+      - name: Deploy on StorefrontCloud.io
+        run: |
+          if curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} -H 'Content-Type: application/json' -X POST -d '{"code":"${{ env.INSTANCE_CODE }}","frontContainerVersion":"${{ github.sha }}"}' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
+            echo "Instance updated"
+          else
+            echo "Deployment failed"
+            exit 1
+          fi
+      - name: Update deployment status (success)
+        if: success()
+        uses: chrnorm/deployment-status@releases/v1
+        with:
+          token: "${{ github.token }}"
+          target_url: ${{ env.CANARY_URL }}
+          state: "success"
+          description: Congratulations! The deploy is done.
+          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
+      - name: Update deployment status (failure)
+        if: failure()
+        uses: chrnorm/deployment-status@releases/v1
+        with:
+          token: "${{ github.token }}"
+          target_url: ${{ env.CANARY_URL }}
+          description: Unfortunately, the instance hasn't been updated.
+          state: "failure"
+          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
